export enum PassengerFlags {
    FRONT_MALE = 1,
    FRONT_FEMALE = 2,
    REAR_LEFT_MALE = 4,
    REAR_LEFT_FEMALE = 8,
    REAR_MIDDLE_MALE = 16,
    REAR_MIDDLE_FEMALE = 32,
    REAR_RIGHT_MALE = 64,
    REAR_RIGHT_FEMALE = 128,
}